#!/bin/bash

# dotfiles_setup.sh
# This script installs dotfiles and terminal configurations

echo "Setting up dotfiles..."

# Get the directory where this script is located
DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Function to backup and symlink a file
link_file() {
    local source="$1"
    local target="$2"
    
    # Create backup if the file already exists and is not a symlink
    if [ -f "$target" ] || [ -d "$target" ]; then
        if [ ! -L "$target" ]; then
            echo "Backing up $target to $target.backup"
            mv "$target" "$target.backup"
        else
            echo "Removing existing symlink $target"
            rm "$target"
        fi
    fi
    
    # Create the symlink
    echo "Creating symlink: $target -> $source"
    ln -s "$source" "$target"
}

# Symlink dotfiles
link_file "$DOTFILES_DIR/.zshrc" "$HOME/.zshrc"
link_file "$DOTFILES_DIR/.gitconfig" "$HOME/.gitconfig"
link_file "$DOTFILES_DIR/.gitignore_global" "$HOME/.gitignore_global"
link_file "$DOTFILES_DIR/.wezterm.lua" "$HOME/.wezterm.lua"
link_file "$DOTFILES_DIR/.tmux.conf" "$HOME/.tmux.conf"

# Install tmux plugin manager if not already installed
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
    echo "Installing tmux plugin manager..."
    mkdir -p "$HOME/.tmux/plugins"
    git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
fi

# Setup powerlevel10k if not already set up
if [ ! -f "$HOME/.p10k.zsh" ]; then
    echo "Setting up powerlevel10k..."
    # Create a basic p10k config - user can customize by running p10k configure
    cat > "$HOME/.p10k.zsh" << 'EOL'
# Generated by Powerlevel10k configuration wizard
# For customization options, run `p10k configure` in the terminal.
# Basic configuration with lean style
typeset -g POWERLEVEL9K_MODE=nerdfont-complete
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=false
typeset -g POWERLEVEL9K_DIR_BACKGROUND=0  # Use black background for directory
EOL
    echo "Created basic p10k config. Run 'p10k configure' to customize it further."
fi

echo "Dotfiles setup complete!"

# Source the zshrc to apply changes
echo "To apply all changes, restart your terminal or run: source ~/.zshrc"
